name: ndaru_flutter
description: "Submission Ilham Andaru Prabowo Front-End Flutter"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    # assets:
    #     - assets/images/

    fonts:
        - family: DMSans
          fonts:
              - asset: assets/fonts/DMSans-Regular.ttf
        - family: PlayfairDisplay
          fonts:
              - asset: assets/fonts/PlayfairDisplay-Regular.ttf
